// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgSrwiMnXBVEhX0i6yPNHevZszYkTcOrI',
    appId: '1:646780424862:web:16c03f97f9e1ce48bc618f',
    messagingSenderId: '646780424862',
    projectId: 'smart-physico',
    authDomain: 'smart-physico.firebaseapp.com',
    storageBucket: 'smart-physico.firebasestorage.app',
    measurementId: 'G-TG8Z562DZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjAikQTrsFt1vpnrWAL_ugTCyXLFGKTz0',
    appId: '1:646780424862:android:98dd9673725d1ab8bc618f',
    messagingSenderId: '646780424862',
    projectId: 'smart-physico',
    storageBucket: 'smart-physico.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVj1hsEr6Ws2LxYi3ezqX52i-tUSEQR88',
    appId: '1:646780424862:ios:43df17d1632ebaccbc618f',
    messagingSenderId: '646780424862',
    projectId: 'smart-physico',
    storageBucket: 'smart-physico.firebasestorage.app',
    iosClientId: '646780424862-ndr020th6ii03k8vkmrajig1hj265ca6.apps.googleusercontent.com',
    iosBundleId: 'com.smartphysio.smartPhysio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVj1hsEr6Ws2LxYi3ezqX52i-tUSEQR88',
    appId: '1:646780424862:ios:43df17d1632ebaccbc618f',
    messagingSenderId: '646780424862',
    projectId: 'smart-physico',
    storageBucket: 'smart-physico.firebasestorage.app',
    iosClientId: '646780424862-ndr020th6ii03k8vkmrajig1hj265ca6.apps.googleusercontent.com',
    iosBundleId: 'com.smartphysio.smartPhysio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgSrwiMnXBVEhX0i6yPNHevZszYkTcOrI',
    appId: '1:646780424862:web:a2c07eccd17a69c6bc618f',
    messagingSenderId: '646780424862',
    projectId: 'smart-physico',
    authDomain: 'smart-physico.firebaseapp.com',
    storageBucket: 'smart-physico.firebasestorage.app',
    measurementId: 'G-44J5GP90RY',
  );

}